package nosharing_test

import (
	"testing"

	"safetylint/internal/nosharing"

	"golang.org/x/tools/go/analysis/analysistest"
)

func TestNosharing(t *testing.T) {
	testdata := analysistest.TestData()
	analysistest.Run(t, testdata, nosharing.Analyzer,
		"bad_capture",
		"good_local_freemu",
		"bad_ptrarg",
		"bad_global",
		"bad_freeze_send",
		"bad_freeze_recv",
		"bad_mutex_unlockedread",
		"bad_mutex_partial",
		"bad_rwmutex",
		"bad_rwmutex_write_under_rlock",
		"bad_globalfreeze",
		"bad_twomutex",
		"bad_trylock",
		"bad_mutex_wrapper",
		"bad_global_freemu_partial",
		"bad_atomic_mix",
		"bad_partition_overlap",
		"bad_partition_read",
		"bad_initreg",
		"bad_dyngo",
		"bad_dyngo_export",
		"bad_wg_sibling",
		"bad_once_unsync",
		"bad_byte_mutate",
		"good_channels",
		"good_freeze",
		"good_readonly",
		"good_nested_client",
		"bad_nested_write",
		"good_waitgroup",
		"good_valuechan",
		"good_mutexstruct",
		"good_mutex_parent",
		"good_mutex_wrapper",
		"good_trylock",
		"good_rwmutex",
		"good_globalinit",
		"good_globalmain",
		"good_globalmutex",
		"good_global_method",
		"good_global_freemu",
		"good_global_read",
		"good_global_atomic",
		"good_atomic_share",
		"good_atomic_filter",
		"good_partition_buf",
		"good_global_errmethod",
		"good_global_mapsvalues",
		"good_broadcast",
		"good_dyngo",
		"good_initreg",
		"good_filprice",
		"good_rwcache",
		"good_once_lazy",
		"good_wg_join",
		"good_retry_slice",
		"initreg",
		"bad_global_httpserve",
		"good_handle_register",
		"good_local_dyngo",
		"good_nested_dyngo",
		"good_wg_localmu",
		"bad_wg_localmu_unlocked",
		"good_freeze_slice",
		"sharero",
		"sharemu",
		"sharewrap",
		"bad_xpkg_readonly",
		"bad_xpkg_mutex",
		"bad_xpkg_wrap",
		"good_xpkg_mutex",
		"bad_afterfunc",
		"bad_afterfunc_callback",
		"good_afterfunc",
		"good_afterfunc_mutex",
		"bad_handlefunc",
		"bad_initgo",
		"good_initgo",
		"plainlib",
		"hotlib",
		"bad_init_xpkg",
		"bad_init_xpkg_nomu",
		"bad_init_xpkg_readhot",
		"good_init_xpkg",
		"good_init_xpkg_read",
		"good_context",
		"good_httpserver",
		"good_stdlib_read",
		"bad_buffer_write",
		"good_nolint",
		"bad_nolint_nounsafe",
		"good_initshare_locked",
		"good_initshare_atomic",
		"good_initshare_chan",
		"bad_initshare_write",
		"good_frozen_field",
		"bad_frozen_field",
		"good_iface_arg",
		"bad_iface_arg",
		"good_field_mutex",
		"bad_field_mutex",
		"good_cancel_unlock",
		"bad_cancel_unlock",
		"good_bufpool",
		"good_range_part",
		"bad_range_part",
		"good_ws_proxy",
		"bad_ws_twowriter",
		"good_promise",
		"good_wg_readonly",
	)
}

func TestNosharingNoFactsLocalReg(t *testing.T) {
	t.Setenv("SAFETYLINT_NO_FACTS", "1")
	testdata := analysistest.TestData()
	analysistest.Run(t, testdata, nosharing.Analyzer, "good_localreg")
}

func TestNosharingNoFactsResiduals(t *testing.T) {
	t.Setenv("SAFETYLINT_NO_FACTS", "1")
	testdata := analysistest.TestData()
	analysistest.Run(t, testdata, nosharing.Analyzer,
		"good_iface_arg",
		"good_wg_readonly",
		"good_range_part",
	)
}
