package nosharing_test

import (
	"testing"

	"safetylint/internal/nosharing"

	"golang.org/x/tools/go/analysis/analysistest"
)

func TestNosharing(t *testing.T) {
	testdata := analysistest.TestData()
	analysistest.Run(t, testdata, nosharing.Analyzer,
		"bad_capture",
		"bad_mutex",
		"bad_ptrarg",
		"bad_global",
		"bad_freeze_send",
		"bad_freeze_recv",
		"bad_mutex_unlockedread",
		"bad_mutex_partial",
		"bad_rwmutex",
		"bad_rwmutex_write_under_rlock",
		"bad_globalfreeze",
		"bad_twomutex",
		"bad_trylock",
		"bad_mutex_wrapper",
		"bad_global_freemu_partial",
		"bad_atomic_mix",
		"bad_partition_overlap",
		"bad_partition_read",
		"bad_initreg",
		"bad_dyngo",
		"good_channels",
		"good_freeze",
		"good_readonly",
		"good_nested_client",
		"bad_nested_write",
		"good_waitgroup",
		"good_valuechan",
		"good_mutexstruct",
		"good_mutex_parent",
		"good_mutex_wrapper",
		"good_trylock",
		"good_rwmutex",
		"good_globalinit",
		"good_globalmain",
		"good_globalmutex",
		"good_global_method",
		"good_global_freemu",
		"good_global_read",
		"good_global_atomic",
		"good_atomic_share",
		"good_atomic_filter",
		"good_partition_buf",
		"good_global_errmethod",
		"good_global_mapsvalues",
		"good_broadcast",
		"good_dyngo",
		"good_initreg",
		"initreg",
		"bad_global_httpserve",
		"sharero",
		"sharemu",
		"sharewrap",
		"bad_xpkg_readonly",
		"bad_xpkg_mutex",
		"bad_xpkg_wrap",
		"good_xpkg_mutex",
		"bad_afterfunc",
		"bad_handlefunc",
		"bad_initgo",
		"good_initgo",
		"plainlib",
		"hotlib",
		"bad_init_xpkg",
		"bad_init_xpkg_nomu",
		"bad_init_xpkg_readhot",
		"good_init_xpkg",
		"good_init_xpkg_read",
		"good_context",
		"good_httpserver",
	)
}
